#!/usr/bin/env python3

import click
from snpScore import snpAnn

@click.command()
@click.option('--gene_bed',
              type=click.Path(exists=True, dir_okay=False),
              help='gene position bedfile.',
              required=True)
@click.option('--snp_ann_dir',
              type=click.Path(exists=True, file_okay=False),
              help='snp annotation directory.',
              required=True)
@click.option('-vcf',
              '--vcf_table_files',
              help='vcf hd5 files, seperated with ",".',
              required=True,
              type=click.STRING)
@click.option('-g',
              '--group_labels',
              help='vcf file groups, seperated with ",".',
              type=click.STRING,
              default='')
@click.option('--outdir',
              type=click.Path(),
              help='output directory.',
              required=True)
@click.option('--genes',
              type=click.STRING,
              help=('show snp information on the genes provided, '
                    'seperated with ",".'),
              default=None)
@click.option('--position',
              type=click.STRING,
              help='show snp information on provided position.',
              default=None)
@click.option('--outfmt',
              type=click.STRING,
              help='results format [table/string].',
              default='table')
def main(gene_bed, snp_ann_dir, outdir, genes, position, vcf_table_files,
         group_labels, outfmt):
    snpAnn.snp_ann_pipe(gene_bed, snp_ann_dir, outdir, genes, position, vcf_table_files,
         group_labels, outfmt=outfmt)

if __name__ == "__main__":
    main()
