#!/usr/bin/env python3

import click
import json
from pathlib import Path
from snpScore import core, snpStats


@click.command()
@click.option(
    '-p',
    '--parameters',
    help='snpScore parameters json string.',
    required=True,
    type=click.STRING
)
@click.option(
    '-d',
    '--data_dir',
    help='vcf hd5 file directory.',
    required=True,
    type=click.Path(exists=True, file_okay=False)
)
@click.option(
    '-o',
    '--outdir',
    help='results directory.',
    required=True,
    type=click.Path()
)
def main(parameters,
         data_dir,
         outdir):
    parameters_obj = json.loads(parameters)
    group_labels = snpStats.groups_from_params(parameters_obj)
    vcf_table_files = snpStats.vcfs_from_params(parameters_obj, data_dir)
    outdir = Path(outdir)
    outdir_suffix = snpStats.outdir_suffix_from_params(
        parameters_obj)
    full_outdir = outdir / outdir_suffix
    snp_score_obj = core.SNPscore(vcf_table_files,
                                  group_labels,
                                  full_outdir,
                                  parameters_obj.get('mutant_freq_low'),
                                  parameters_obj.get('wild_freq_low'),
                                  parameters_obj.get('mutant_parent_freq_low'),
                                  parameters_obj.get('wild_parent_freq_low'),
                                  parameters_obj.get('background_freq_low'),
                                  parameters_obj.get('mutant_freq_up'),
                                  parameters_obj.get('wild_freq_up'),
                                  parameters_obj.get('mutant_parent_freq_up'),
                                  parameters_obj.get('wild_parent_freq_up'),
                                  parameters_obj.get('background_freq_up'),
                                  parameters_obj.get('min_depth'),
                                  parameters_obj.get('snp_number_window'),
                                  parameters_obj.get('snp_number_step'),
                                  parameters_obj.get('genome_window'),
                                  parameters_obj.get('genome_step'),
                                  parameters_obj.get('methods'))
    snp_score_obj.run


if __name__ == '__main__':
    main()
