#!/usr/bin/env python3

import click
import json
from loguru import logger
from pathlib import Path
from snpScore import tableFromVcf, sample_and_group
from snpScore import tableFromSelectTable
from snpScore import snpTableMP, async_batch_sh_jobs
from snpScore import snpScoreBox, qtlSeqr, CHR_SIZE
from snpScore import outdir_suffix_from_params
from snpScore import freq2qtlseqr


@click.command()
@click.option('--vcf_dir',
              help=('vcf table directory, can be more than one '
                    '[--vcf_dir dir1 --vcf_dir dir2].'),
              type=click.Path(exists=True, file_okay=False),
              multiple=True)
@click.option('--vcf_ann_dir',
              help='snp annotation file dir.',
              type=click.Path(exists=True, file_okay=False),
              default=None)
@click.option('-m',
              '--mutant',
              help='mutant sample ids, seperated with comma.',
              type=click.STRING,
              required=True)
@click.option('-w',
              '--wild',
              help='wild sample ids, seperated with comma.',
              type=click.STRING,
              required=True)
@click.option('-o',
              '--outdir',
              help='results directory.',
              required=True,
              type=click.Path())
@click.option('--chrom',
              help='chromosome id.',
              required=True,
              type=click.STRING)
@click.option('-t',
              '--thread',
              help='Max thread for this program to use.',
              default=4)
@click.option('-mp',
              '--mutant_parent',
              help='mutant parent sample ids, seperated with comma.',
              type=click.STRING,
              default='')
@click.option('-wp',
              '--wild_parent',
              help='wild parent sample ids, seperated with comma.',
              type=click.STRING,
              default='')
@click.option('-bg',
              '--background',
              help='background sample ids, seperated with comma.',
              type=click.STRING,
              default='')
@click.option('--chr_size',
              help='chr size file, default is chr size of bread wheat.',
              type=click.Path(exists=True, dir_okay=False),
              default=CHR_SIZE)
@click.option('--ref_freq',
              help=('filter out SNPs with a '
                    'Reference Allele Frequency '
                    'less than refAlleleFreq '
                    'and greater than 1 - refAlleleFreq.'),
              default=0.43,
              type=click.FLOAT)
@click.option('--p_ref_freq',
              help=('filter out parent SNPs with a '
                    'Reference Allele Frequency '
                    'less than refAlleleFreq '
                    'and greater than 1 - refAlleleFreq.'),
              default=0.43,
              type=click.FLOAT)
@click.option('--background_ref_freq',
              help=('filter out background SNPs with a '
                    'Reference Allele Frequency '
                    'less than refAlleleFreq '
                    'and greater than 1 - refAlleleFreq.'),
              default=0.43,
              type=click.FLOAT)
@click.option('--mutant_alt_exp',
              help='mutant alt frequency expectation.',
              default=None,
              type=click.FLOAT)
@click.option('--wild_alt_exp',
              help='wild alt frequency expectation.',
              default=None,
              type=click.FLOAT)
@click.option('--min_depth',
              help='minimal read depth for a site to include in analysis.',
              default=5,
              type=click.INT)
@click.option('--snp_number_window',
              help='snp number slidewindow window size.',
              default=20,
              type=click.INT)
@click.option('--snp_number_step',
              help='snp number slidewindow step size.',
              default=5,
              type=click.INT)
@click.option('--filter_method',
              help=('varscore filter method'),
              default='nonsymmetrical',
              type=click.STRING)
@click.option('--qtlseqr', is_flag=True, help='Run qtlseqr analysis.')
@click.option('--ed', is_flag=True, help='Run snp ED analysis.')
@click.option('--qtlseqr_window',
              help='snp window size for calculation.',
              default=1e7,
              type=click.INT)
@click.option('--qtlseqr_window',
              help='snp window size for calculation.',
              default=1e7,
              type=click.INT)
@click.option('--pop_stru',
              help=('the population structure. '
                    'Defaults to "F2" and assumes "RIL" otherwise.'),
              default='RIL',
              type=click.STRING)
@click.option('--qtlseqr_ref_freq',
              help='qtlseqr ref freq.',
              default=0.3,
              type=click.FLOAT)
@click.option('--qtlseqr_min_depth',
              help='qtlseqr min depth.',
              default=5,
              type=click.INT)
def main(vcf_dir, mutant, wild, outdir, thread, mutant_parent, wild_parent,
         background, mutant_alt_exp, wild_alt_exp, min_depth,
         snp_number_window, snp_number_step, vcf_ann_dir, qtlseqr_window,
         ref_freq, pop_stru, qtlseqr, ed, p_ref_freq, background_ref_freq,
         chr_size, chrom, filter_method, qtlseqr_ref_freq, qtlseqr_min_depth):
    sample_list, group_list = sample_and_group(mutant, wild, mutant_parent,
                                               wild_parent, background)

    outdir = Path(outdir)
    results_dir = outdir / f'split/{chrom}'

    snp_table_obj = snpTableMP(out_dir=results_dir,
                               table_dirs=vcf_dir,
                               samples=sample_list,
                               sample_label=group_list,
                               min_depth=min_depth,
                               chrom=chrom)

    snp_score_methods = ['var']

    vcf_ann_file = Path(vcf_ann_dir) / f'{chrom}' / 'snp.ann.table.pkl'

    snpscore_obj = snpScoreBox(alt_freq_df=snp_table_obj.alt_freq_df,
                               grp_list=group_list,
                               method_list=snp_score_methods,
                               outdir=results_dir,
                               chr_size=chr_size,
                               min_depth=min_depth,
                               snp_number_window=snp_number_window,
                               snp_number_step=snp_number_step,
                               ref_freq=ref_freq,
                               p_ref_freq=p_ref_freq,
                               background_ref_freq=background_ref_freq,
                               mutant_alt_exp=mutant_alt_exp,
                               wild_alt_exp=wild_alt_exp,
                               vcf_ann_file=vcf_ann_file,
                               filter_method=filter_method)
    snpscore_obj.score_jobs
    if qtlseqr or ed:
        qtlseqr_snp_table = freq2qtlseqr(snp_table_obj.alt_freq_file)
        qtlseqr_obj = qtlSeqr(input_table=qtlseqr_snp_table,
                              window=qtlseqr_window,
                              ref_freq=qtlseqr_ref_freq,
                              pop_stru=pop_stru,
                              min_sample_dp=qtlseqr_min_depth,
                              out_dir=results_dir,
                              run_qtlseqr=qtlseqr,
                              run_ed=ed,
                              web=True)
        qtlseqr_obj.launch_job


if __name__ == '__main__':
    main()
