#!/usr/bin/env python3

import click
from snpScore import core


@click.command()
@click.option(
    '-vcf',
    '--vcf_table_files',
    help='vcf hd5 files, seperated with ",".',
    required=True,
    type=click.STRING
)
@click.option(
    '--vcf_ann_file',
    help='snp annotation file.',
    required=True,
    type=click.Path()
)
@click.option(
    '-g',
    '--group_labels',
    help='vcf file groups, seperated with ",".',
    type=click.STRING,
    required=True
)
@click.option(
    '-o',
    '--outdir',
    help='results directory.',
    required=True,
    type=click.Path()
)
@click.option(
    '--mutant_alt_exp',
    help='mutant alt frequency expectation.',
    default=None,
    type=click.FLOAT
)
@click.option(
    '--wild_alt_exp',
    help='wild alt frequency expectation.',
    default=None,
    type=click.FLOAT
)
@click.option(
    '--mutant_parent_alt_exp',
    help='mutant parent alt frequency expectation.',
    default=None,
    type=click.FLOAT
)
@click.option(
    '--wild_parent_alt_exp',
    help='wild parent alt frequency expectation.',
    default=None,
    type=click.FLOAT
)
@click.option(
    '--background_alt_exp',
    help='background alt frequency expectation.',
    default=None,
    type=click.FLOAT
)
@click.option(
    '--min_depth',
    help='minimal read depth for a site to include in analysis.',
    default=5,
    type=click.INT
)
@click.option(
    '--snp_number_window',
    help='snp number slidewindow window size.',
    default=20,
    type=click.INT
)
@click.option(
    '--snp_number_step',
    help='snp number slidewindow step size.',
    default=5,
    type=click.INT
)
@click.option(
    '--methods',
    help='snp score calculation methods.',
    default='var,snp_index',
    type=click.STRING
)
@click.option(
    '--qtlseqr_window',
    help='snp window size for calculation.',
    default=1e7,
    type=click.INT
)
@click.option(
    '--qtlseqr_window',
    help='snp window size for calculation.',
    default=1e7,
    type=click.INT
)
@click.option(
    '--qtlseqr_ref_freq',
    help=('filter out SNPs with a Reference Allele Frequency '
          'less than refAlleleFreq and greater than 1 - refAlleleFreq.'),
    default=0.3,
    type=click.FLOAT
)
@click.option(
    '--pop_stru',
    help='the population structure. Defaults to "F2" and assumes "RIL" otherwise.',
    default='RIL',
    type=click.STRING
)
def main(vcf_table_files,
         group_labels,
         outdir,
         mutant_alt_exp,
         wild_alt_exp,
         mutant_parent_alt_exp,
         wild_parent_alt_exp,
         background_alt_exp,
         min_depth,
         snp_number_window,
         snp_number_step,
         methods,
         vcf_ann_file,
         qtlseqr_window,
         qtlseqr_ref_freq,
         pop_stru):
    snp_score_obj = core.SNPscore(vcf_table_files=vcf_table_files,
                                  vcf_ann_file=vcf_ann_file,
                                  group_labels=group_labels,
                                  outdir=outdir,
                                  mutant_alt_exp=mutant_alt_exp,
                                  wild_alt_exp=wild_alt_exp,
                                  mutant_parent_alt_exp=mutant_parent_alt_exp,
                                  wild_parent_alt_exp=wild_parent_alt_exp,
                                  background_alt_exp=background_alt_exp,
                                  min_depth=min_depth,
                                  snp_number_window=snp_number_window,
                                  snp_number_step=snp_number_step,
                                  methods=methods,
                                  qtlseqr_window=qtlseqr_window,
                                  qtlseqr_ref_freq=qtlseqr_ref_freq,
                                  pop_stru=pop_stru)
    snp_score_obj.run


if __name__ == '__main__':
    main()
