#!/usr/bin/env python3

import fire
import json
import pandas as pd
from pathlib import Path
from snpScore import tableFromVcf

ANN_TABLE_COL = ("#CHROM", "POS", "REF", "ALT", "INFO")

def getAnn(info):
    return info.split('ANN=')[1]

def vcfAnn(vcfFile, annoFile):
    annoFile = Path(annoFile)
    ann_df = pd.read_csv(vcfFile, sep='\t', header=None, comment="#", dtype={0: str})
    ann_df = ann_df.loc[:, [0, 1, 3, 4, 7]]
    ann_df.columns = ANN_TABLE_COL
    ann_df.loc[:, 'INFO'] = ann_df.INFO.map(getAnn)
    if annoFile.is_file():
        old_ann_df = pd.read_pickle(annoFile)
        ann_df = pd.concat([ann_df, old_ann_df])
        ann_df.drop_duplicates(subset=["#CHROM", "POS", "ALT"], inplace=True)
    ann_df.to_pickle(annoFile)


def splitVcf(vcfFile, splitDir,thread=1, sample_prefix=None):
    vcf2tb_obj = tableFromVcf(vcf=vcfFile, out_dir=splitDir, thread=thread, sample_prefix=sample_prefix)
    vcf2tb_obj.make_table
    return vcf2tb_obj.vcf_samples


def main(vcfFile, splitDir, annoFile, thread=1, sample_prefix=None):
    Path(splitDir).mkdir(parents=True, exist_ok=True)
    vcfAnn(vcfFile, annoFile)
    sample_names = splitVcf(vcfFile, splitDir, thread, sample_prefix)
    print(json.dumps(sample_names))


if __name__ == "__main__":
    fire.Fire(main)
